Feature/prepare release210 (#109)
* 1. Prepare for release Core ; Selenium; Security; WebApi 2. Tune pom.xml

* wait.until  resolved. And now struggling with java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.toImmutableSet()

* 1.Resolved issue with Guava lib  2.In Chrome driver - switch from DesiredCapabilities to ChromeOptions